const INVISIBLE_PEV_OPENING_SQUARE_BRACKET_COLUMN_TITLE = " " // No-break space
const INVISIBLE_PEV_CLOSING_ANGLE_BRACKET_COLUMN_TITLE = " "  // Narrow no-break space

export {
    INVISIBLE_PEV_OPENING_SQUARE_BRACKET_COLUMN_TITLE,
    INVISIBLE_PEV_CLOSING_ANGLE_BRACKET_COLUMN_TITLE,
}
