const INVISIBLE_VECTOR_OPENING_SQUARE_BRACKET_COLUMN_TITLE = " " // No-break space
const INVISIBLE_VECTOR_CLOSING_ANGLE_BRACKET_COLUMN_TITLE = " " // Narrow no-break space

export {
    INVISIBLE_VECTOR_OPENING_SQUARE_BRACKET_COLUMN_TITLE,
    INVISIBLE_VECTOR_CLOSING_ANGLE_BRACKET_COLUMN_TITLE,
}
