const INVISIBLE_MONZO_OPENING_SQUARE_BRACKET_COLUMN_TITLE = " " // No-break space
const INVISIBLE_MONZO_CLOSING_ANGLE_BRACKET_COLUMN_TITLE = " "  // Narrow no-break space

export {
    INVISIBLE_MONZO_OPENING_SQUARE_BRACKET_COLUMN_TITLE,
    INVISIBLE_MONZO_CLOSING_ANGLE_BRACKET_COLUMN_TITLE,
}
